# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ConnectionHealth_pb2 as ConnectionHealth__pb2


class HealthStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A gRPC.Channel.
        """
        self.ping = channel.unary_unary(
                '/Health/ping',
                request_serializer=ConnectionHealth__pb2.PingRequest.SerializeToString,
                response_deserializer=ConnectionHealth__pb2.PingReply.FromString,
                )


class HealthServicer(object):
    """Missing associated documentation comment in .proto file"""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=ConnectionHealth__pb2.PingRequest.FromString,
                    response_serializer=ConnectionHealth__pb2.PingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Health/ping',
                                             ConnectionHealth__pb2.PingRequest.SerializeToString,
                                             ConnectionHealth__pb2.PingReply.FromString,
                                             options, channel_credentials,
                                             call_credentials, compression, wait_for_ready, timeout, metadata)
