# Generated by the grpc Python protocol compiler plugin. DO NOT EDIT!
import grpc

import DueTasksProvider_pb2 as DueTasksProvider__pb2


class ProviderStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_unary(
                '/Provider/subscribe',
                request_serializer=DueTasksProvider__pb2.Subscription.SerializeToString,
                response_deserializer=DueTasksProvider__pb2.SubscriptionResponse.FromString,
                )
        self.listen = channel.unary_stream(
                '/Provider/listen',
                request_serializer=DueTasksProvider__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=DueTasksProvider__pb2.DueTasksResponse.FromString,
                )


class ProviderServicer(object):
    """Missing associated documentation comment in .proto file"""

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listen(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=DueTasksProvider__pb2.Subscription.FromString,
                    response_serializer=DueTasksProvider__pb2.SubscriptionResponse.SerializeToString,
            ),
            'listen': grpc.unary_stream_rpc_method_handler(
                    servicer.listen,
                    request_deserializer=DueTasksProvider__pb2.SubscriptionRequest.FromString,
                    response_serializer=DueTasksProvider__pb2.DueTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Provider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Provider(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Provider/subscribe',
                                             DueTasksProvider__pb2.Subscription.SerializeToString,
                                             DueTasksProvider__pb2.SubscriptionResponse.FromString,
                                             options, channel_credentials,
                                             call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Provider/listen',
                                              DueTasksProvider__pb2.SubscriptionRequest.SerializeToString,
                                              DueTasksProvider__pb2.DueTasksResponse.FromString,
                                              options, channel_credentials,
                                              call_credentials, compression, wait_for_ready, timeout, metadata)
