# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DueTasksProvider.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DueTasksProvider.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\003genB\025DueTasksProviderProto',
  serialized_pb=b'\n\x16\x44ueTasksProvider.proto\"\'\n\x13SubscriptionRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"L\n\x14SubscriptionResponse\x12\x0f\n\x07\x64ueTask\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.SubscriptionStatus\"K\n\x0cSubscription\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x18\n\x04type\x18\x03 \x03(\x0e\x32\n.EventType\"U\n\x10\x44ueTasksResponse\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.EventType\x12\x16\n\x0e\x64ueTaskMessage\x18\x03 \x01(\t*B\n\tEventType\x12\x0e\n\nASSIGNMENT\x10\x00\x12\x08\n\x04TEST\x10\x01\x12\x1b\n\x17PREPARATION_FOR_CLASSES\x10\x02*I\n\x07Subject\x12\x17\n\x13\x44ISTRIBUTED_SYSTEMS\x10\x00\x12\x16\n\x12KERNEL_PROGRAMMING\x10\x01\x12\r\n\tCOMPILERS\x10\x02*/\n\x12SubscriptionStatus\x12\x0e\n\nSUCCESSFUL\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32r\n\x08Provider\x12\x31\n\tsubscribe\x12\r.Subscription\x1a\x15.SubscriptionResponse\x12\x33\n\x06listen\x12\x14.SubscriptionRequest\x1a\x11.DueTasksResponse0\x01\x42\x1c\n\x03genB\x15\x44ueTasksProviderProtob\x06proto3'
)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ASSIGNMENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREPARATION_FOR_CLASSES', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
_SUBJECT = _descriptor.EnumDescriptor(
  name='Subject',
  full_name='Subject',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTED_SYSTEMS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KERNEL_PROGRAMMING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPILERS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=377,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_SUBJECT)

Subject = enum_type_wrapper.EnumTypeWrapper(_SUBJECT)
_SUBSCRIPTIONSTATUS = _descriptor.EnumDescriptor(
  name='SubscriptionStatus',
  full_name='SubscriptionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESSFUL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=452,
  serialized_end=499,
)
_sym_db.RegisterEnumDescriptor(_SUBSCRIPTIONSTATUS)

SubscriptionStatus = enum_type_wrapper.EnumTypeWrapper(_SUBSCRIPTIONSTATUS)
ASSIGNMENT = 0
TEST = 1
PREPARATION_FOR_CLASSES = 2
DISTRIBUTED_SYSTEMS = 0
KERNEL_PROGRAMMING = 1
COMPILERS = 2
SUCCESSFUL = 0
ERROR = 1



_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='SubscriptionRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)


_SUBSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='SubscriptionResponse',
  full_name='SubscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dueTask', full_name='SubscriptionResponse.dueTask', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='SubscriptionResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=143,
)


_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='Subscription.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='Subscription.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Subscription.type', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=220,
)


_DUETASKSRESPONSE = _descriptor.Descriptor(
  name='DueTasksResponse',
  full_name='DueTasksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='DueTasksResponse.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='DueTasksResponse.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dueTaskMessage', full_name='DueTasksResponse.dueTaskMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=307,
)

_SUBSCRIPTIONRESPONSE.fields_by_name['status'].enum_type = _SUBSCRIPTIONSTATUS
_SUBSCRIPTION.fields_by_name['type'].enum_type = _EVENTTYPE
_DUETASKSRESPONSE.fields_by_name['type'].enum_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['SubscriptionResponse'] = _SUBSCRIPTIONRESPONSE
DESCRIPTOR.message_types_by_name['Subscription'] = _SUBSCRIPTION
DESCRIPTOR.message_types_by_name['DueTasksResponse'] = _DUETASKSRESPONSE
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
DESCRIPTOR.enum_types_by_name['Subject'] = _SUBJECT
DESCRIPTOR.enum_types_by_name['SubscriptionStatus'] = _SUBSCRIPTIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONREQUEST,
  '__module__' : 'DueTasksProvider_pb2'
  # @@protoc_insertion_point(class_scope:SubscriptionRequest)
  })
_sym_db.RegisterMessage(SubscriptionRequest)

SubscriptionResponse = _reflection.GeneratedProtocolMessageType('SubscriptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONRESPONSE,
  '__module__' : 'DueTasksProvider_pb2'
  # @@protoc_insertion_point(class_scope:SubscriptionResponse)
  })
_sym_db.RegisterMessage(SubscriptionResponse)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTION,
  '__module__' : 'DueTasksProvider_pb2'
  # @@protoc_insertion_point(class_scope:Subscription)
  })
_sym_db.RegisterMessage(Subscription)

DueTasksResponse = _reflection.GeneratedProtocolMessageType('DueTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _DUETASKSRESPONSE,
  '__module__' : 'DueTasksProvider_pb2'
  # @@protoc_insertion_point(class_scope:DueTasksResponse)
  })
_sym_db.RegisterMessage(DueTasksResponse)


DESCRIPTOR._options = None

_PROVIDER = _descriptor.ServiceDescriptor(
  name='Provider',
  full_name='Provider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=501,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='Provider.subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIPTION,
    output_type=_SUBSCRIPTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listen',
    full_name='Provider.listen',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_DUETASKSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROVIDER)

DESCRIPTOR.services_by_name['Provider'] = _PROVIDER

# @@protoc_insertion_point(module_scope)
